import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:myshubamuhurtham/MyComponents/my_components.dart';
import 'package:myshubamuhurtham/MyComponents/my_theme.dart';

class TermsConditionScreen extends StatefulWidget {
  const TermsConditionScreen({super.key});

  @override
  State<TermsConditionScreen> createState() => _TermsConditionScreenState();
}

class _TermsConditionScreenState extends State<TermsConditionScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: MyComponents.appbarWithTitle(
          context, MyComponents.appName, true, [], MyTheme.whiteColor),
      body: SingleChildScrollView(
        child: Column(children: [
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              'Terms and Conditions',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: RichText(
              text: TextSpan(
                  text:
                      'If you require any clarification about these terms, please contact ',
                  style: GoogleFonts.inter(
                      fontSize: 18,
                      letterSpacing: 0.4,
                      color: MyTheme.blackColor),
                  children: [
                    WidgetSpan(
                        child: InkWell(
                      onTap: () {
                        MyComponents.launchInEmail(MyComponents.emailAddress);
                      },
                      child: Text(
                        '${MyComponents.emailAddress} ',
                        style: GoogleFonts.inter(
                            fontSize: 18,
                            letterSpacing: 0.4,
                            color: MyTheme.baseColor),
                      ),
                    )),
                    TextSpan(
                      text:
                          'and obtain such clarification before using this website. This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and the terms and conditions for access or usage of www.myshubamuhurtham.com (the "Website"). PLEASE READ THE FOLLOWING TERMS AND CONDITIONS VERY CAREFULLY BEFORE USING THE WEBSITE. ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE IMPLIES YOUR AGREEMENT TO BE BOUND BY ALL THESE TERMS AND CONDITIONS ("Agreement"). If you do not want to be bound by the Terms and Conditions, you must not use the Website or the MYSHUBAMUHURTHAM Services. The Terms and Conditions also includes the applicable policies which are incorporated herein by way of reference and as amended from time to time (the "Terms and conditions"). In these Terms, references to "MYSHUBAMUHURTHAM member" shall mean the end user accessing the Website/MYSHUBAMUHURTHAM services, its contents or using the MYSHUBAMUHURTHAM Services offered. MYSHUBAMUHURTHAM member also includes persons such as father, mother, brother, sister, relative or a friend ("Registrant") of the prospective bride/ bridegroom. The terms "You" and "User" shall be interchangeably used for "MYSHUBAMUHURTHAM member".',
                      style: GoogleFonts.inter(
                          fontSize: 18,
                          letterSpacing: 0.4,
                          color: MyTheme.blackColor),
                    ),
                  ]),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              'Scope',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              'You understand and acknowledge that MYSHUBAMUHURTHAM acts as an "Intermediary" as defined under clause (1) sub-clause (w) of Section 2 of the Information Technology Act, 2000. MYSHUBAMUHURTHAM is a brand owned by myshubamuhurtham.com Limited (MCL) which owns, retains and has complete rights in MYSHUBAMUHURTHAM and the MYSHUBAMUHURTHAM Website /App/ MYSHUBAMUHURTHAM Service. MYSHUBAMUHURTHAM acts as a platform to enable any user to themselves register on it (by filling the mandatory fields and optional fields, if any) to voluntarily search for profile(s) from the database of MYSHUBAMUHURTHAM’s already registered users, for seeking prospective lawful matrimonial alliances for themselves. MYSHUBAMUHURTHAM retail store may also be able to assist you to create your profile, however, you must have a valid/operational mobile phone number and an email id. The profiles in the database of MYSHUBAMUHURTHAM are classified broadly on the basis of language and region for the ease and convenience of its member / customer. MYSHUBAMUHURTHAM Members are provided with free/paid access for searching profiles from the database of MYSHUBAMUHURTHAM, as per the partner preference set by you (on the Website/Applications -(App) and you can shortlist the profiles in which you are interested.',
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '1. Eligibility',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              'A) MYSHUBAMUHURTHAMMembership and rights of admission is reserved solely for : I. Indian Nationals & Citizens. II. Persons of Indian Origin (PIO). III. Non Resident Indians (NRI). IV. Persons of Indian Descent or Indian Heritage V. Persons who intend to marry persons of Indian Origin. B) Further in capacity as MYSHUBAMUHURTHAM member you confirm that you are : I. 18 years or above (if you are a woman) or 21 years or above (if you are a man); II. If you have applied for Divorce, you may register on our website/App by stating "Awaiting Divorce". III. If you are a resident of any other Country, you are legally competent to marry as per the local rules applicable to your country and you shall comply with the Indian laws for marrying a person of Indian Origin C) In case you are a Registrant of the prospective bride/ bridegroom and has created profile in MYSHUBAMUHURTHAM Website/App on behalf of them or is accessing the MYSHUBAMUHURTHAM Website/App on behalf of them implies that you have taken their consent for their profile creation in MYSHUBAMUHURTHAM and for accessing the MYSHUBAMUHURTHAM Website/App.',
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '2. Registration',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. We expect that you would complete the online registration process with fairness and honesty in furnishing true, accurate, current, complete information and with providing recent photos of you which will help you to meet your parameters .We expect you to read the relevant column before keying in the details or selecting the option available or uploading the photo. You are requested not to key in details of the profile in field other than the applicable field (including mentioning id's of other platforms/websites/App or repeating your details in another fields, after filling them once in the relevant fields or others photographs. In order to serve you better if MYSHUBAMUHURTHAM requires additional details you agree to provide it. You may also give a missed call to any of our retail outlets phone number for us to call you back and assist you in getting your profile registered on our website/App. Further you may fill in your email id and phone number in any of our registration campaigns appearing in various websites as part of our advertisements, basis which you may receive call from our Customer Service Center and assist you in getting your profile registered on our website/App. MYSHUBAMUHURTHAM may also reproduce your profile information in other matrimonial websites owned by MCL including community based websites to provide better matching Profiles to you. B. If at any point of time MYSHUBAMUHURTHAM comes to know or is so informed by third party or has reasons to believe that any information provided by you for registration (including photos) or otherwise is found to be untrue, inaccurate, or incomplete,MYSHUBAMUHURTHAM shall have full right to suspend or terminate (without any notice) your MYSHUBAMUHURTHAM membership and forfeit any amount paid by you towards MYSHUBAMUHURTHAM membership fee and refuse to provide MYSHUBAMUHURTHAM service to you thereafter. C. MYSHUBAMUHURTHAM also reserves the right to block the registration of your profile on Website/App, if any, in the case of your contact details/links being entered in irrelevant fields or if there are errors in any data entered by the MYSHUBAMUHURTHAM members in their profile. D. Registration of duplicate profiles of the same person is not allowed in MYSHUBAMUHURTHAM Website/App. MYSHUBAMUHURTHAM shall have full right to suspend or terminate (without any notice) such duplicate profile. E. You acknowledge and confirm that your registration with MYSHUBAMUHURTHAM and the usage of MYSHUBAMUHURTHAM services is with the bonafide intention of marriage and not otherwise. MYSHUBAMUHURTHAM Membership is restricted strictly to the registered MYSHUBAMUHURTHAM individual member only. Organizations, companies, businesses and/or individuals carrying on similar or competitive business cannot become Members of MYSHUBAMUHURTHAM and nor use the MYSHUBAMUHURTHAM Service or MYSHUBAMUHURTHAM members data for any commercial purpose, and MYSHUBAMUHURTHAM reserves its right to initiate appropriate legal action for breach of these obligation.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '3. Account Security',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "You are responsible for safeguarding the confidentiality of your MYSHUBAMUHURTHAM login credentials such as your user id, password, OTP, etc., and for restricting access to your computer/mobile to prevent unauthorized access to your account. We, as a Company do not ask for Password and you are cautioned not to share your password to any persons. You agree to accept responsibility for all activities that occur under your account.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '4. Role and Responsibility of MYSHUBAMUHURTHAM',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. MYSHUBAMUHURTHAM reproduces your details once you register on our website /App on 'as is as available' basis and also share your profile with other registered MYSHUBAMUHURTHAM members within website(s) of MCL.. B. MYSHUBAMUHURTHAM's obligation is only to provide an interface to its registered members to search their prospect themselves without any assistance. C. The profile search conducted by any MYSHUBAMUHURTHAM member and the matches shown thereof are automatically generated by MYSHUBAMUHURTHAM, and based on the partner preference set by you. In the event of MYSHUBAMUHURTHAM member changing their partner preference on the Website/App, then the automated system generated prospect results of the Website/App may also undergo corresponding change. D. MYSHUBAMUHURTHAM does not prohibit any MYSHUBAMUHURTHAM member from sending interest to your profile or communicating to you based on their partner preference. But you are at the liberty to deny their interest or proceed further if you are interested. E. MYSHUBAMUHURTHAM cannot guarantee or assume responsibility for any specific results from the use of the data available from the MYSHUBAMUHURTHAM service or from other matrimonial websites owned by MCL including community based websites.. F. MYSHUBAMUHURTHAM shall safeguard sensitive user information using security standards,authentication mechanisms, access controls and encryption techniques. G. MYSHUBAMUHURTHAM cannot guarantee the complete protection of user data while it is in transit, or prevent any tampering of the data by a third party with malicious intent before the data reaches the MYSHUBAMUHURTHAM servers. H. MYSHUBAMUHURTHAM has a special safety feature for women, called 'Secure Connect', which enables women to take control of their privacy and safety while searching for their life partner. 'Secure Connect' has a calling feature that lets the women in MYSHUBAMUHURTHAM receive calls from men who have premium membership without revealing their contact numbers to them, It is upto to the women to respond to the other party and MYSHUBAMUHURTHAM has no control over the same. I. MYSHUBAMUHURTHAM do not authenticate/endorse any information of any profile and hence you as a user need to verify the credentials and information provided by other users.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '5. Role and Responsibility of MYSHUBAMUHURTHAM Member',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. You, shall safeguard your profile information by creating a strong password during profile creation with combination of alphabets, both upper and lower case and numbers. B. Any information / data required by MYSHUBAMUHURTHAM for using the MYSHUBAMUHURTHAM services shall be provided by the MYSHUBAMUHURTHAM Member, as and when so sought by MYSHUBAMUHURTHAM. C. You are requested to verify the credentials of the prospect, exercise due care and caution regarding their profile information which includes marital status, educational qualifications, financial status, occupation, character, health status, etc. and satisfy yourself before making a choice of your match. MYSHUBAMUHURTHAM shall not be liable for short coming due to any misrepresentations made by any of its MYSHUBAMUHURTHAM members. D. You are required to verify the credentials of the prospect and we shall not be liable for any misbehavior/ misrepresentations made by the Prospect to you during video call. Please check 'Safe Matrimony' link in the website/Apps for guidance. E. To get better search results, MYSHUBAMUHURTHAM Members are expected to provide latest photograph which should not be more than 3 (three) months old. Providing old photographs/ photographs of others, inaccurate / false information shall be treated as violation of terms and conditions and MYSHUBAMUHURTHAM shall retain their right under clause 2 (b) of this terms and conditions. F. MYSHUBAMUHURTHAM members are expected to disclose their health records during profile enrollment which includes any pre-existing illness, physical disability etc. Non - disclosure at the time of enrollment shall be treated as violation of the terms and conditions and MYSHUBAMUHURTHAM shall retain their right under clause 2 (b) of this terms and conditions. G. MYSHUBAMUHURTHAM Members are advised to refrain from : i. Entering into any financial transactions with prospects. MYSHUBAMUHURTHAM Members shall not seek financial help or provide financial help from / to the other MYSHUBAMUHURTHAM Members ii. Using abusive language when they communicate with the other MYSHUBAMUHURTHAM Members iii. being discriminative or using racial comments etc. iv. Sharing of confidential and personal data with each other but not limited to sharing of bank details, etc. v. Entering into physical relationship with any prospect before marriage. vi. violating any law for the time being in force. vii. From mentioning details of other matrimonial services while sending personalized messages H. MYSHUBAMUHURTHAM members are expected to visit our website for understanding the safety measures on partner search and awareness towards online safety. I. MYSHUBAMUHURTHAM Members are expected to be cautious of prospects who ask for favours, money etc or call from multiple phone numbers, only interact over phone, doesn't come forward for face to face meeting (physically or through video calls) and don’t involve family and friends in match making. Beware of suspended profiles status before you finalize an alliance with the prospect. J. The MYSHUBAMUHURTHAM members agrees that for getting effective search results of prospects on Website/App you will regularly log in to the profile maintained in the Website/App and send expression of interest which is an automated messages to prospects as a free MYSHUBAMUHURTHAM member, and in the event you have availed paid MYSHUBAMUHURTHAM package, you can send personalized messages to prospects to show your expression of interest/replies. MYSHUBAMUHURTHAM member also may review the expression of interest sent to you / read the messages sent to you by prospects and may respond suitably. K. You also agree that while accessing / using the Website/App, you will be guided by the terms and conditions of the Website/App including but not limited to the use of feature of website /App like chat instantly with prospect, viewing horoscope of prospects, enhancing privacy settings (photo/horoscope/phone number) or for viewing social and professional profile of members on their Facebook, LinkedIn, etc. L. If the MYSHUBAMUHURTHAM Member fails to update in MYSHUBAMUHURTHAM website/App, any change in the particulars furnished in their profile/ then the MYSHUBAMUHURTHAM membership may be suspended by MYSHUBAMUHURTHAM at its sole discretion. M. MYSHUBAMUHURTHAM member shall, in case of finalization of his/her/their Registrant’s marriage, delete their profile by themselves or intimate MYSHUBAMUHURTHAM for removal/deletion of their profile. N. MYSHUBAMUHURTHAM Members agree to use secure devices, software and networks in a private place for accessing the MYSHUBAMUHURTHAM services. O. MYSHUBAMUHURTHAM member shall not use any kind of Bots like web robots, Chatbot or any other automated processes/programs/scripts to use, communicate or respond in MYSHUBAMUHURTHAM Website/App. P. MYSHUBAMUHURTHAM Members shall not probe, scan or test the vulnerabilities of the MYSHUBAMUHURTHAM Website/App or any network connected to the Website/App nor breach the security measures instituted by MYSHUBAMUHURTHAM. Q. You shall also not make any payment / transfer any amount to account of any MCL employees. All payments shall be made only to MYSHUBAMUHURTHAM account. R. MYSHUBAMUHURTHAM members are expected to approach MCL to resolve their complaints and grievances and shall not air their grievance/complaints in social media.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '6. Medium of Communication to MYSHUBAMUHURTHAM Members',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. MYSHUBAMUHURTHAM member hereby consents for receiving communication including promotional communications through any medium of communications such as electronic mails, calls, SMS or through Whatsapp messages from MCL or other portals owned by MCL or their alliance partners. B. MYSHUBAMUHURTHAM by its automatic system sends to its member (s) profile (s) of the prospect by way of images/ documents/ messages / links. MYSHUBAMUHURTHAM member confirms that the mobile number su MyShubamuhurthamitted to it for verification or alternative number if any provided, is not registered with the Do Not Disturb / National Customer Preference Register and they shall not initiate any complaint. MYSHUBAMUHURTHAM Member further confirms that even if MYSHUBAMUHURTHAM Member is registered with the telecom service provider under the category Do Not Disturb / National Customer Preference Register the calls from MYSHUBAMUHURTHAM either to the verified mobile number or alternative number if any provided shall not be treated as promotional calls. C. You are also entitled to set up your communications frequency from MYSHUBAMUHURTHAM, like - only on weekends or fortnightly etc. You may also opt for not getting any call from MYSHUBAMUHURTHAM by ticking the appropriate box in the Website/App, provided that, you agree to receive calls from Relationship Manager of Assisted Matrimony/ Elite Matrimony for contacting you as a shortlisted profile for their registered members.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '7. Confidentiality',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "Any feedback you provide to MYSHUBAMUHURTHAM shall be deemed to be non-confidential. MYSHUBAMUHURTHAM shall be free to use such feedback/information on an unrestricted basis. Further, by su MyShubamuhurthamitting the feedback, you represent and warrant that (i) your feedback does not contain confidential or proprietary information of yourself or third parties; (ii) MYSHUBAMUHURTHAM member is not under any obligation of confidentiality, express or implied, with respect to the feedback; (iii) you are not entitled to any compensation or reimbursement of any kind from MYSHUBAMUHURTHAM for the feedback under any circumstances.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '8. Privacy of Membership',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "To protect your privacy and understand our practices as amended from time to time , please read and follow our Privacy Policy which also governs your visit to MYSHUBAMUHURTHAM and other websites owned by MCL, the personal information / data provided to us by you during the course of usage of MYSHUBAMUHURTHAM will be treated as confidential and in accordance with the Privacy policy and applicable laws and regulations. If you object to your information being transferred or used, please do not use the website.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '9. Disputes between Members',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. MYSHUBAMUHURTHAM Members are solely responsible for the communications (through any medium) with prospect or vice versa. MYSHUBAMUHURTHAM expressly disclaims any responsibility or liability for any monetary transaction(s) or exchange(s) or interaction(s) or passing of information(s) etc. between any MYSHUBAMUHURTHAM members inter se via e-mail, chat, interaction, Whatsapp or any other medium of communication between MYSHUBAMUHURTHAM members either using website /App or otherwise. B. MYSHUBAMUHURTHAM has no obligation, to monitor any such disputes arising between the MYSHUBAMUHURTHAM members, and MYSHUBAMUHURTHAM shall not be party to any such dispute/litigation etc. C. MYSHUBAMUHURTHAM is not a broker or the agent of any MYSHUBAMUHURTHAM member, and MYSHUBAMUHURTHAM does not partake in the exchange of any kind of discussion between the MYSHUBAMUHURTHAM members and prospects or the results of their discussion.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '10. Third Party website',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. MYSHUBAMUHURTHAM member understand and agree that MYSHUBAMUHURTHAM may allow third parties to put up advertisements on the MYSHUBAMUHURTHAM application/Website and MYSHUBAMUHURTHAM does not control the contents of such third party advertisement on the MYSHUBAMUHURTHAM application/Website. Third party websites to which links are given on Website/App are not governed by these Terms and conditions and all such third party websites are governed by their own terms and conditions for use and privacy policy, and in case of conflict the terms and conditions of the third party website shall prevail. The Company does not in any manner whatsoever authenticate, endorse, verify or certify these third party websites or any contents therein. Please note that a user shall click on links to third party websites at his / her sole risk and responsibility. B. The MYSHUBAMUHURTHAM members agrees and understands that MYSHUBAMUHURTHAM may also allow third parties to provide MYSHUBAMUHURTHAM members services on the website/App like horoscope matching etc., and MYSHUBAMUHURTHAM may also collect the payment for such third party services to you, and MYSHUBAMUHURTHAM in this regard can have revenue sharing arrangement with such third party, however in no event shall MYSHUBAMUHURTHAM be liable to you for such third party services. C. MYSHUBAMUHURTHAM reserves the right to add/delete/alter/modify/suspend any or all the MYSHUBAMUHURTHAM Services at any time as it may deem fit, without notice. The MYSHUBAMUHURTHAM members are expected to see the change on the Website/App.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '11. Limitation of liability',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. MCL / MYSHUBAMUHURTHAM or its Office bearers shall under no circumstances be liable or responsible to the MYSHUBAMUHURTHAM member or his/her authorized Representative or Registrant or any third party for any direct, indirect, special, exemplary, incidental, or consequential damages of any character including, without limitation, damages resulting from the use of our Website/App/Third Party Website/ MYSHUBAMUHURTHAM services. B. MYSHUBAMUHURTHAM informs you that the exchange of profile(s) through or by MYSHUBAMUHURTHAM should not in any way be construed as a matrimonial offer and/or recommendation and / or advice or guarantee given to the MYSHUBAMUHURTHAM member, from/ or by MYSHUBAMUHURTHAM. C. Notwithstanding anything to the contrary contained herein, MYSHUBAMUHURTHAM's liability to you for any cause whatsoever, and regardless of the form of the action, will at all times be limited to the amount paid, if any, by you to MYSHUBAMUHURTHAM, for any specific MYSHUBAMUHURTHAM paid package, and no further.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '12. MCL / MYSHUBAMUHURTHAM will not be liable in case of any wrong/improper match made due to unavailability of profiles from MYSHUBAMUHURTHAM/MCL’s owned other websites.',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '13. MCL / MYSHUBAMUHURTHAM or its office bearers shall under no circumstances be liable, if any, for the MYSHUBAMUHURTHAM member entering into financial transaction with any other MYSHUBAMUHURTHAM Member or any third party.',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '14. MCL / MYSHUBAMUHURTHAM or its office bearers shall under no circumstances be liable, if any, for any MYSHUBAMUHURTHAM members not responding/reciprocating when you approach them for matrimonial alliance.',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '18. Class Action Suits',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "You acknowledge and confirm that you will not bring or participate in any class action or other class proceeding in connection with any dispute with MYSHUBAMUHURTHAM. Further neither you nor MYSHUBAMUHURTHAM agrees to class arbitration.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '19. General',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "In the event you file a false complaint against another prospect on our Website /App and consequently we have suspended/deleted that prospects profile based on your complaint, then we reserve our right to initiate appropriate legal (Civil/Criminal) action against you and claim any and all costs expenses from you, for such irresponsible/misrepresentation/illegal/unlawful action. We also reserve our right to suspend your profile and forfeit any and all amounts paid by you for the MYSHUBAMUHURTHAM services as per clause 2 (b) of these terms and conditions.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: RichText(
              text: TextSpan(children: [
                TextSpan(
                  text: "20. ",
                  style: GoogleFonts.rubik(
                      fontSize: 20,
                      letterSpacing: 0.4,
                      fontWeight: FontWeight.w600,
                      color: MyTheme.blackColor),
                ),
                TextSpan(
                  text:
                      "Notwithstanding anything contained herein, MYSHUBAMUHURTHAM reserves the absolute right to delete, in any manner as it deems fit, any content of any profile listing placed on MYSHUBAMUHURTHAM/website/App (once such instance come to MYSHUBAMUHURTHAM notice) in order to ensure, that proper consent has been obtained by you , prima facie accuracy and the prevailing laws in force for the time being, especially those relating to providing any obscene, libelous, blasphemous, slanderous, defamatory or invasive of another person’s (deceased or alive) right of privacy or publicity, or that may reasonably be deemed to be harmful, vulgar, pornographic, abusive, harassing, threatening, hateful, objectionable with respect to race, religion, creed, nationality, gender or otherwise unfit for reproduction; or suggests or encourages unfair or illegal /indecent, unlawful activity. MYSHUBAMUHURTHAM also reserves the right to block/ delete / suspend the profile which might be offensive, illegal or that might violate the rights, harm or threaten the safety of our office bearers/employees (including undue communication with any employee) and/or other registered prospects or using our MYSHUBAMUHURTHAM website/App as a means of communication while sending messages to other MYSHUBAMUHURTHAM members regarding their profile identity in other matrimonial websites.",
                  style: GoogleFonts.inter(
                      fontSize: 18,
                      letterSpacing: 0.4,
                      color: MyTheme.blackColor),
                )
              ]),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: RichText(
              text: TextSpan(children: [
                TextSpan(
                  text: "21. ",
                  style: GoogleFonts.rubik(
                      fontSize: 20,
                      letterSpacing: 0.4,
                      fontWeight: FontWeight.w600,
                      color: MyTheme.blackColor),
                ),
                TextSpan(
                  text:
                      "Once your paid membership expires, you cannot avail the unexpired balance phone call count/ unexpired SMS . Similarly, you cannot access the already viewed MYSHUBAMUHURTHAM member(s) contact information unless you renew your account within 30 days.",
                  style: GoogleFonts.inter(
                      fontSize: 18,
                      letterSpacing: 0.4,
                      color: MyTheme.blackColor),
                )
              ]),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: RichText(
              text: TextSpan(children: [
                TextSpan(
                  text: "22. ",
                  style: GoogleFonts.rubik(
                      fontSize: 20,
                      letterSpacing: 0.4,
                      fontWeight: FontWeight.w600,
                      color: MyTheme.blackColor),
                ),
                TextSpan(
                  text:
                      "However on renewal, the unexpired phone call / SMS shall be carried forward to your account from the last day of expiry.",
                  style: GoogleFonts.inter(
                      fontSize: 18,
                      letterSpacing: 0.4,
                      color: MyTheme.blackColor),
                )
              ]),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: RichText(
              text: TextSpan(children: [
                TextSpan(
                  text: "23. ",
                  style: GoogleFonts.rubik(
                      fontSize: 20,
                      letterSpacing: 0.4,
                      fontWeight: FontWeight.w600,
                      color: MyTheme.blackColor),
                ),
                TextSpan(
                  text:
                      "In case of conflict between the terms and condition of Website/App and terms and conditions of any other website including other websites of MCL, the terms and condition of MYSHUBAMUHURTHAM Website/App shall prevail for the service provided through this Website/App.",
                  style: GoogleFonts.inter(
                      fontSize: 18,
                      letterSpacing: 0.4,
                      color: MyTheme.blackColor),
                )
              ]),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '24. Disclaimer',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              'A. Your access to and use of the MYSHUBAMUHURTHAM Services or any content is at your own risk. YOU UNDERSTAND AND AGREE THAT THE MYSHUBAMUHURTHAMSERVICES ARE PROVIDED TO YOU ON AN "AS IS" AND "AS AVAILABLE" BASIS. WITHOUT LIMITING THE FOREGOING, TO THE FULL EXTENT PERMITTED BY LAW, MYSHUBAMUHURTHAMDISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. MYSHUBAMUHURTHAM does not warrant that the Website/App, its servers, or e-mail sent from MYSHUBAMUHURTHAM are free of viruses or other harmful components. MYSHUBAMUHURTHAM will not be liable for any damages of any kind arising from the use of this MYSHUBAMUHURTHAM Website/App, including, but not limited to direct, indirect, incidental, punitive, and consequential damages. B. MYSHUBAMUHURTHAM does not give any implied or explicit guarantee or warranty of marriage or alliance by you choosing to register on our Website/App and using MYSHUBAMUHURTHAM services (both paid and free). C. Notwithstanding anything contrary contained anywhere, under no circumstances, MYSHUBAMUHURTHAM shall be held responsible or liable whatsoever or howsoever, arising out of, relating to or connected with: i. any act or omission done by MYSHUBAMUHURTHAM/MCL/payment gateway/alliance partner etc.; ii. any untrue or incorrect information MyShubamuhurthamitted by you or on your behalf; iii. any decision taken by you or on your behalf or any consequences thereof, based on any information provided by any other user (including suspension/deletion of the profile from MYSHUBAMUHURTHAM); iv. any unauthorized or illegal act done by any third party relating to or connected with any information MyShubamuhurthamitted by you or on your behalf; v. any cyber crime attempted or committed by anyone and vi. any incident of force-majeure or "act of god". vii. Any issue already stated in these terms and conditions including limitation of liability clause of these terms and conditions. viii. Using/availing of third party services namely horoscope matching services etc. and for paying them through the Website. ix. MYSHUBAMUHURTHAM shall not be liable for the outcome of during any interaction in a meeting, call, sms, chat, email or social media posts at any point of time x. Any issues relating to any technical malfunction of any telecommunication network, software, hardware failures, network congestion, denial of service, failure due to spamming or any combination of the above. D. You expressly agree that your use of this Website/App is at your sole risk. E. We are not liable to you for any damage or alteration to your equipment including but not limited to computer equipment, hand-held device or mobile telephones as a result of the installation or use of the app. We are not liable to you for any damage or alteration to your equipment including but not limited to computer equipment, hand-held device or mobile telephones as a result of the installation or use of the app.',
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '25. Indemnity',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "By using our MYSHUBAMUHURTHAM services you agree to defend, indemnify, and hold harmless MYSHUBAMUHURTHAM, its subsidiaries, affiliates, Directors, officers, agents, and other partners and employees, fully indemnified and harmless from any loss, damage, liability, claim, or demand, including reasonable attorney's fees, made by any person through improper use of the service provided by MYSHUBAMUHURTHAM. This defence and indemnification obligation will survive in perpetuity.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '26. Termination',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. We/ MYSHUBAMUHURTHAM in good faith reserve our right to terminate your MYSHUBAMUHURTHAM membership or suspend/delete your profile at our sole discretion without any notice to you and take any action as mentioned in clause 2 (b) of the Terms and Conditions, in case you I. seek physical / financial favors from our other registered members or II. have provided incorrect information on our website/App or III. have committed any fraudulent/ unlawful/ illegal activities through the use of our website/App or IV. have violated this Terms and conditions or V. have misappropriated the name, likeness, email address, contact no or other personally identifiable information of another MYSHUBAMUHURTHAM member created a profile on our website /App by impersonation/ fake/ bogus/ false/ misrepresentation/ without consent of the person who’s profile is being registered or use only part information including using photo of third parties without the permission of such third parties or act with other members/employees in indecent/improper manner, B. If MYSHUBAMUHURTHAM receives any complaint against you and consequently we have suspended/deleted your profile in good faith, then we shall not be liable to you in any manner whatsoever, including for any loss, costs, expenses, or consequence, if any. C. Unless otherwise provided in these Terms and Conditions, MYSHUBAMUHURTHAM membership may be terminated by MYSHUBAMUHURTHAM / you without assigning any reasons by serving 7 ( seven) days written notice on the other, all amount paid till date by you to MYSHUBAMUHURTHAM shall be forfeited. D. Upon termination / suspension of MYSHUBAMUHURTHAM membership, your right to use or access the MYSHUBAMUHURTHAM Website/App MYSHUBAMUHURTHAM services will cease immediately. All provisions of this terms and conditions that by their nature should survive termination shall survive termination, including, without limitation, disclaimers, and limitations of liability. Termination of your access to and use of the MYSHUBAMUHURTHAM Services shall not relieve you of any obligations arising or accruing prior to such termination.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '27. Jurisdiction and Applicable Law',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. The registration of MYSHUBAMUHURTHAM membership and all MYSHUBAMUHURTHAM services are deemed to have been entered into within the territorial Jurisdiction of Chennai, India. B. The MYSHUBAMUHURTHAM Members unconditionally agree that all such disputes and / or differences if any shall be governed by the Laws of India and MyShubamuhurtham to the exclusive Jurisdiction of appropriate court of law in Coimbatore, Tamil Nadu, India.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '28. Mode of Payment',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. Payment made by cash / cheque / Net Banking / Debit / Credit Card/ Paypal/ RTGS/ NEFT/ would be in accordance with the prevailing RBI guidelines. Activation of paid MYSHUBAMUHURTHAM service shall be subject to realization of the said payment. In case of dishonor of Cheque/demand draft; you shall be liable to pay applicable bank’s cheque/DD bouncing charges. Further MYSHUBAMUHURTHAM service to your account will be deactivated / suspended until you settle the value of the payment and applicable bank charges in cash. B. MYSHUBAMUHURTHAM uses third party payment gateways for collection payment through credit/debit card or other payment instruments. You agree to provide us with your Permanent Account Number / Form 60/61 of the Income Tax Act, 1961 and rules thereunder in the event you choose any paid package of MCL, the value of such paid package being Rs.2,00,000/- [Rupees Two Lakh Only] and above from MCL. You agree to provide us with your Permanent Account Number / Form 60/61 of the Income Tax Act, 1961 and rules thereunder in the event you choose any paid package of MCL, the value of such paid package being Rs.2,00,000/- [Rupees Two Lakh Only] and above from MCL.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '29. Refund and Assignment',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. The payments made by any MYSHUBAMUHURTHAM member to MCL by way of membership / renewal fee / auto renewal are treated as non-refundable. B. MYSHUBAMUHURTHAM member shall not assign or transfer your MYSHUBAMUHURTHAM membership to any other person or entity, and such an act shall be treated as violation of terms and conditions and MYSHUBAMUHURTHAM shall retain their right under clause 2 (b) of this terms and conditions. C. Payment once made for MYSHUBAMUHURTHAM services cannot be assigned to any person/party or adjusted towards any other product or packages provided by the Company.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '30. Renewal',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: RichText(
              text: TextSpan(
                  text:
                      "A. We automatically renew all paid Memberships before the expiry of the term of the paid Membership. You agree that your account will be subject to this automatic renewal feature B. When you first subscribe for your paid Membership, you acknowledge that when your paid Membership expires it will automatically renew for the duration and at the last paid price. C. The maximum tenure of any packages will be 12 (Twelve) month. Every MYSHUBAMUHURTHAM packages post validity period (varies from package to package), shall be renewed. D. If you do not want your paid membership to automatically renew, you must cancel your paid membership. In case you have to mail for cancellation, mail to cancellation ",
                  style: GoogleFonts.inter(
                      fontSize: 18,
                      letterSpacing: 0.4,
                      color: MyTheme.blackColor),
                  children: [
                    WidgetSpan(
                        child: InkWell(
                      onTap: () {
                        MyComponents.launchInEmail(
                            MyComponents.cancelEmailAddress);
                      },
                      child: Text(
                        '${MyComponents.cancelEmailAddress}.',
                        style: GoogleFonts.inter(
                            fontSize: 18,
                            letterSpacing: 0.4,
                            color: MyTheme.baseColor),
                      ),
                    )),
                  ]),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(
                left: 8.0, right: 8.0, top: 10.0, bottom: 10.0),
            child: Text(
              '31. Additional terms and conditions applicable to Non- Resident Indian customers.',
              style: GoogleFonts.rubik(
                  fontSize: 20,
                  letterSpacing: 0.4,
                  fontWeight: FontWeight.w600,
                  color: MyTheme.blackColor),
            ),
          ),
          Container(
            width: MyComponents.widthSize(context),
            margin: const EdgeInsets.only(left: 8.0, right: 8.0),
            child: Text(
              "A. Jurisdiction The laws of India shall be applicable. B. Arbitration of Disputes. The Parties shall discuss among themselves and resolve any disputes informally. We are interested in attempting to resolve any Disputes by amicable and informal means, and we encourage you to contact us before resorting to arbitration. If the dispute is not resolved within 30 ( thirty ) days from the date of such dispute , then such dispute may only be resolved through an individual arbitration conducted in accordance with the provisions of The Arbitration and conciliation Act, 1996, by sole arbitrator. The seat of Arbitration shall be Chennai, Tamil Nadu, India. We shall appoint the sole arbitrator. The arbitration proceedings shall be conducted in the English language C. However, Disputes relating to infringement of our intellectual property rights, which we may elect to have resolved by means other than arbitration. D. In case of Renewal, Customer is charged the current price that prevails and renewed is done only for 3 months duration irrespective of the past package. E. Enforcement Any proceeding to enforce this arbitration agreement may be brought in Courts of Chennai, Tamil Nadu India.",
              style: GoogleFonts.inter(
                  fontSize: 18, letterSpacing: 0.4, color: MyTheme.blackColor),
            ),
          ),
        ]),
      ),
    );
  }
}
